# Baremetal Tests for Earlgrey

baremetal-eg-tests:
  tags:
    - qemu_ot
  stage: test
  needs:
    - "build-clang"
    - project: rv/sandbox/rot/baremetal_test
      job: build-eg
      ref: $BAREMETAL_REF
      artifacts: true
  variables:
    BASEDIR: bmtests/eg
    CI_EXEC: 1
  script:
    - python3 -m virtualenv .venv
    - . .venv/bin/activate
    - pip3 install -r scripts/opentitan/requirements.txt
    - rm -rf ${BASEDIR}
    - mkdir -p ${BASEDIR}
    - zstd -d --stdout ot-eg-bmtest.tar.zst | tar xf - -C ${BASEDIR}
    - find ${BASEDIR}
    - scripts/opentitan/pyot.py -vv -c ${BASEDIR}/data/qemu/ot-earlgrey/pyot-eflash.hjson
         -w ot-earlgrey.csv -R -T 3
  artifacts:
    public: false
    expire_in: 1 year
    name: "bm-ot-earlgrey"
    paths:
      - ot-earlgrey.csv
